/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155VaultProxy } from "./ERC1155VaultProxy";
export type { ERC721VaultProxy } from "./ERC721VaultProxy";
export type { VaultProxy } from "./VaultProxy";
