/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ERC721VaultProxy,
  ERC721VaultProxyInterface,
} from "../../../../src/beacon/VaultProxy.sol/ERC721VaultProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_beacon",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "DelegationFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "InitializationFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beacon",
        type: "address",
      },
    ],
    name: "BeaconSet",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60803460b757601f6102dc38819003918201601f19168301916001600160401b0383118484101760bb5780849260209460405283398101031260b757516001600160a01b0381169081810360b757811560a8577fa3f0ad74e5423aebfd80d3ef4346578335a9a72aeaee59ff6cb3582b35133d5055604051907f367184f1bb13aa656fb065e5e2b1104b30f71206d03961639cac77f3a6b331765f80a261020c90816100d08239f35b63d92e233d60e01b5f5260045ffd5b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe60806040526004361015610015575b3661011d57005b5f3560e01c6301ffc9a70361000e57346100cb5760203660031901126100cb5760043563ffffffff60e01b81168091036100cb5760206001600160a01b0361005b610141565b16916024604051809481936301ffc9a760e01b835260048301525afa80156100d7575f90610096575b604051901515815280602081015b0390f35b506020813d6020116100cf575b816100b0602093836100dc565b810103126100cb575180151581036100cb5761009290610084565b5f80fd5b3d91506100a3565b610112565b90601f8019910116810190811067ffffffffffffffff8211176100fe57604052565b634e487b7160e01b5f52604160045260245ffd5b6040513d5f823e3d90fd5b5f80610127610141565b368280378136915af43d5f803e1561013d573d5ff35b3d5ffd5b7fa3f0ad74e5423aebfd80d3ef4346578335a9a72aeaee59ff6cb3582b35133d5054604051635c60da1b60e01b815290602090829060049082906001600160a01b03165afa9081156100d7575f91610197575090565b90506020813d6020116101ce575b816101b2602093836100dc565b810103126100cb57516001600160a01b03811681036100cb5790565b3d91506101a556fea26469706673582212208682e0208824832abeadff5beabaac562d0dffa6729a6747cf2dc2a29e3e6c1a64736f6c634300081c0033";

type ERC721VaultProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC721VaultProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC721VaultProxy__factory extends ContractFactory {
  constructor(...args: ERC721VaultProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _beacon: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_beacon, overrides || {});
  }
  override deploy(
    _beacon: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_beacon, overrides || {}) as Promise<
      ERC721VaultProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERC721VaultProxy__factory {
    return super.connect(runner) as ERC721VaultProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC721VaultProxyInterface {
    return new Interface(_abi) as ERC721VaultProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC721VaultProxy {
    return new Contract(address, _abi, runner) as unknown as ERC721VaultProxy;
  }
}
