/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155VaultProxy__factory } from "./ERC1155VaultProxy__factory";
export { ERC721VaultProxy__factory } from "./ERC721VaultProxy__factory";
export { VaultProxy__factory } from "./VaultProxy__factory";
