/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155VaultProxy__factory } from "./IERC1155VaultProxy__factory";
export { IERC721VaultProxy__factory } from "./IERC721VaultProxy__factory";
export { IVaultProxy__factory } from "./IVaultProxy__factory";
