/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155VaultBeacon__factory } from "./ERC1155VaultBeacon__factory";
export { ERC721VaultBeacon__factory } from "./ERC721VaultBeacon__factory";
export { VaultBeacon__factory } from "./VaultBeacon__factory";
