/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iVaultProxySol from "./IVaultProxy.sol";
export type { iVaultProxySol };
export type { IDiamondCut } from "./IDiamondCut";
export type { IDiamondLoupe } from "./IDiamondLoupe";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Vault } from "./IERC1155Vault";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC20Token } from "./IERC20Token";
export type { IERC721 } from "./IERC721";
export type { IERC721AExtension } from "./IERC721AExtension";
export type { IERC721AVault } from "./IERC721AVault";
export type { IIsSerialized } from "./IIsSerialized";
export type { IUnvaulted } from "./IUnvaulted";
export type { IVaultBeacon } from "./IVaultBeacon";
export type { IVaultCollectionFactory } from "./IVaultCollectionFactory";
