/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IUnvaultedInterface extends Interface {
  getFunction(nameOrSignature: "isUnvaulted" | "unvault"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isUnvaulted",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unvault",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "isUnvaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unvault", data: BytesLike): Result;
}

export interface IUnvaulted extends BaseContract {
  connect(runner?: ContractRunner | null): IUnvaulted;
  waitForDeployment(): Promise<this>;

  interface: IUnvaultedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isUnvaulted: TypedContractMethod<
    [_nftAddress: AddressLike, tokenId: BigNumberish, proof: BytesLike[]],
    [boolean],
    "view"
  >;

  unvault: TypedContractMethod<
    [_nftAddress: AddressLike, tokenId: BigNumberish, proof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isUnvaulted"
  ): TypedContractMethod<
    [_nftAddress: AddressLike, tokenId: BigNumberish, proof: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "unvault"
  ): TypedContractMethod<
    [_nftAddress: AddressLike, tokenId: BigNumberish, proof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
