/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iVaultProxySol from "./IVaultProxy.sol";
export { IDiamondCut__factory } from "./IDiamondCut__factory";
export { IDiamondLoupe__factory } from "./IDiamondLoupe__factory";
export { IERC1155__factory } from "./IERC1155__factory";
export { IERC1155Vault__factory } from "./IERC1155Vault__factory";
export { IERC165__factory } from "./IERC165__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IERC20Token__factory } from "./IERC20Token__factory";
export { IERC721__factory } from "./IERC721__factory";
export { IERC721AExtension__factory } from "./IERC721AExtension__factory";
export { IERC721AVault__factory } from "./IERC721AVault__factory";
export { IIsSerialized__factory } from "./IIsSerialized__factory";
export { IUnvaulted__factory } from "./IUnvaulted__factory";
export { IVaultBeacon__factory } from "./IVaultBeacon__factory";
export { IVaultCollectionFactory__factory } from "./IVaultCollectionFactory__factory";
