/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721ABurnableUpgradeable } from "./ERC721ABurnableUpgradeable";
export type { IERC721ABurnableUpgradeable } from "./IERC721ABurnableUpgradeable";
