/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { ERC1155Upgradeable__factory } from "./ERC1155Upgradeable__factory";
