/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155VaultBeacon } from "./ERC1155VaultBeacon";
export type { ERC721VaultBeacon } from "./ERC721VaultBeacon";
export type { VaultBeacon } from "./VaultBeacon";
