/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155VaultProxy } from "./IERC1155VaultProxy";
export type { IERC721VaultProxy } from "./IERC721VaultProxy";
export type { IVaultProxy } from "./IVaultProxy";
