/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleVaultBeaconSol from "./SimpleVaultBeacon.sol";
export type { simpleVaultBeaconSol };
import type * as vaultBeaconSol from "./VaultBeacon.sol";
export type { vaultBeaconSol };
import type * as vaultProxySol from "./VaultProxy.sol";
export type { vaultProxySol };
