/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155VaultImplementation } from "./ERC1155VaultImplementation";
export type { ERC721VaultImplementation } from "./ERC721VaultImplementation";
