/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleERC1155VaultBeacon__factory } from "./SimpleERC1155VaultBeacon__factory";
export { SimpleERC721VaultBeacon__factory } from "./SimpleERC721VaultBeacon__factory";
export { SimpleVaultBeacon__factory } from "./SimpleVaultBeacon__factory";
