/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleERC1155VaultBeacon } from "./SimpleERC1155VaultBeacon";
export type { SimpleERC721VaultBeacon } from "./SimpleERC721VaultBeacon";
export type { SimpleVaultBeacon } from "./SimpleVaultBeacon";
